### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#45]
The script worked well for the first 19 subjects, but then I got this systematic error at the DWI step for all remaining subjects:

[err.batch_processing_sub-DEV205Sujet09.log](https://github.com/user-attachments/files/16085325/err.batch_processing_sub-DEV205Sujet09.log)
[err.batch_processing_sub-VS251.log](https://github.com/user-attachments/files/16085326/err.batch_processing_sub-VS251.log)
[Uploading err.batch_processing_sub-TV236.log…]()

~~~
_TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dagher/dagher12/lydia12/SPINE_park/spine-park/aggregate_chunks.py", line 66, in <module>
    main()
  File "/dagher/dagher12/lydia12/SPINE_park/spine-park/aggregate_chunks.py", line 62, in main
    aggregate_data(input_csv, output_csv)
  File "/dagher/dagher12/lydia12/SPINE_park/spine-park/aggregate_chunks.py", line 31, in aggregate_data
    aggregated_df = df.groupby(['Subject', 'VertLevel']).apply(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1846, in apply
    return self._python_apply_general(f, self._obj_with_exclusions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1885, in _python_apply_general
    values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 918, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/dagher/dagher12/lydia12/SPINE_park/spine-park/aggregate_chunks.py", line 35, in <lambda>
    'STD()': (x['Size [vox]'] * x['STD()']).sum() / x['Size [vox]'].sum(),
              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/arraylike.py", line 202, in __mul__
    return self._arith_method(other, operator.mul)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/series.py", line 6115, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/base.py", line 1382, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 283, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 227, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export02/data/lydiac/miniconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 163, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't multiply sequence by non-int of type 'float'__
~~~

**Comment by jcohenadad** [comment]
Can you upload `/dagher/dagher12/lydia12/SPINE_park/CENIR_ICEBERG_BIDS/RESULTS_02072024/results/DWI_FA_53.csv`

**Comment by Kaonashi22** [comment]
[DWI_FA_53.csv](https://github.com/user-attachments/files/16088580/DWI_FA_53.csv)

**Comment by jcohenadad** [comment]
hum... I don't see `sub-DEV205Sujet09` on the CSV, so maybe the issue was actually caused by the subject not being processed with extract metric. 

I will run the script on `sub-DEV205Sujet09` to see if I can reproduce the error.

**Comment by Kaonashi22** [comment]
I ran the script on the two first subjects that failed, sub-DEV203Sujet08 and sub-DEV205Sujet09. I still have the same error. That's weird...

**Comment by jcohenadad** [comment]
can you try to run one of the subject that fails on your laptop? it should take about an hour (use `-job 1 -include-list sub-DEV203Sujet08`)

**Comment by Kaonashi22** [comment]
I can't work on my laptop; I don't have enough storage space left to install the SCT and import the data...
I re-runned on one subject after changing the location of the output directory. It worked. But when I try to run again on multiple subjects, I get the same error...
________________________________

**Comment by jcohenadad** [comment]
Hum... this sounds more like a server-related issue then, but I'm not sure what could be the exact cause. @joshuacwnewton do you have any insights?

**Comment by Kaonashi22** [comment]
I'm still getting the same error :(

[err.batch_processing_sub-DEV203Sujet08.log](https://github.com/user-attachments/files/16102774/err.batch_processing_sub-DEV203Sujet08.log)

**Comment by joshuacwnewton** [comment]
Ah! Looking at the CSV uploaded above, I notice that the STD() column contains a cell with the value `'Weights sum to zero, can't be normalized'`. 

Since this is a string (and not a number), I presume that this is the cause of this specific error.

**Comment by Kaonashi22** [comment]
I'm just adding that it worked for the first 20 subjects I processed before I got the error.
________________________________

**Comment by joshuacwnewton** [comment]
That makes sense, because the `'Weights sum to zero, can't be normalized'` cell only appears with `sub-DEV203Sujet08_chunk-3`, which comes after many other subjects.

(And, since we're appending to the csv, once this cell gets added, it will fail all subjects that come after.)

**Comment by jcohenadad** [comment]
OK, great catch @joshuacwnewton!

@Kaonashi22 can you please send me the problematic subject alongside the derivatives?

**Comment by jcohenadad** [comment]
Problematic line:

<img width="1917" alt="image" src="https://github.com/sct-pipeline/spine-park/assets/2482071/b257cd2d-13dd-4872-86bf-db2cc8431497">

**Comment by jcohenadad** [comment]
The segmentation is correct:
![image](https://github.com/sct-pipeline/spine-park/assets/2482071/d40c55fc-c5f5-4366-8a37-d117be732aa0)

**Comment by jcohenadad** [comment]
The manual disc label files is missing the '12' value (corresponds to T5):
~~~
julien-macbook:~/temp $ sct_label_utils -i /Users/julien/temp/joplin/lydia/CENIR_ICEBERG_spine_BIDS/derivatives/labels/sub-DEV203Sujet08/anat/sub-DEV203Sujet08_T2_label-disc.nii.gz -display

--
Spinal Cord Toolbox (git-master-9e1f65b86902cb237d5f79058a4623eed2d2c8eb)

sct_label_utils -i /Users/julien/temp/joplin/lydia/CENIR_ICEBERG_spine_BIDS/derivatives/labels/sub-DEV203Sujet08/anat/sub-DEV203Sujet08_T2_label-disc.nii.gz -display
--

Position=(170,257,31) -- Value= 1
Position=(166,226,31) -- Value= 2
Position=(163,206,31) -- Value= 3
Position=(156,180,31) -- Value= 4
Position=(149,156,31) -- Value= 5
Position=(140,135,31) -- Value= 6
Position=(138,118,31) -- Value= 7
Position=(134,95,36) -- Value= 8
Position=(140,69,36) -- Value= 9
Position=(149,40,38) -- Value= 10
Position=(156,11,38) -- Value= 11
All labels (useful syntax):
170,257,31,1:166,226,31,2:163,206,31,3:156,180,31,4:149,156,31,5:140,135,31,6:138,118,31,7:134,95,36,8:140,69,36,9:149,40,38,10:156,11,38,11
~~~

Causing only single label for registration:
![image](https://github.com/sct-pipeline/spine-park/assets/2482071/48107a34-1076-4e8b-8ae9-305a7578f814)

The reason that label is missing is likely because the T2 for that subject did not cover T5:

![image](https://github.com/sct-pipeline/spine-park/assets/2482071/9dfbdf61-0d75-496c-a218-c13f7d017490)

We should then revisit our code, because we assume for this project that all subjects have coverage down to T5:

https://github.com/sct-pipeline/spine-park/blob/84ba26feb1c2094e956cc43d808bd857d156d934/batch_processing.sh#L20-L21

I see two options:
1. We adapt the code to deal with the fact that some subjects don't have T5 covered.
2. We replace T5 by the lowest level available in *all* subjects of the study. 

I think that the first option is better, given that the majority of subjects have T5 covered. @Kaonashi22 I let you decide what you prefer.

**Comment by Kaonashi22** [comment]
Thanks for these investigations @jcohenadad !
Then let's go for the first option
