### ISSUE TITLE
Vertebral labeling is unreliable on this dataset using `sct_label_vertebrae`

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-park#9]
Version: https://github.com/sct-pipeline/spine-park/pull/8/commits/9d780cc67cd15519db437dfc48c4878cdc55030b

We should explore alternative approaches. @NathanMolinier do you have a method that we can already use for this project?

**Comment by Kaonashi22** [comment]
Version: 9d780cc

Is this vertebral labeling accurate? The masks don't correspond to the vertebral body

![vertebral_labels](https://github.com/sct-pipeline/spine-park/assets/155473122/44c7fff7-c843-4f33-a6e1-a55d53967cda)

**Comment by jcohenadad** [comment]
> Is this vertebral labeling accurate? The masks don't correspond to the vertebral body

no it is not, hence this issue 😉

**Comment by Kaonashi22** [comment]
True!
I guess the registration to the template is not accurate if the labels are wrong...

**Comment by Kaonashi22** [comment]
This might be a different problem: the vertebral labeling and segmentation failed for this subject. There is a slight lateral curvature at the thoracic level (on coronal views); I don't know if it may impact the process

![1](https://github.com/sct-pipeline/spine-park/assets/155473122/6c4b6e1a-0fa6-4bf8-b265-a146b9771c93)
![2](https://github.com/sct-pipeline/spine-park/assets/155473122/99efe229-0ed6-4b46-ace9-9c1d579c7d05)

**Comment by NathanMolinier** [comment]
Is the data available somewhere ?

**Comment by Kaonashi22** [comment]
Thanks, I can give you some sample images. How can I send them?
________________________________

**Comment by NathanMolinier** [comment]
Maybe using dropbox or google drive ? Also, is it only a T2w contrast for all the images ? And the FOV is only cervical ?

**Comment by Kaonashi22** [comment]
Can I have your email?
I have T2, MT, M2RAGE and diffusion images for ~ 50 subjects
The FOV includes the upper thoracic level until T5-T6
________________________________

**Comment by lydiachougar** [comment]
You may be able to access the images with this link:
https://drive.google.com/file/d/1M187Lh3O-ih5vckSOrEJg12B4ckKBYMQ/view?usp=drive_link

**Comment by jcohenadad** [comment]
Email introduction sent (I suggest to send the data privately)

**Comment by NathanMolinier** [comment]
## Update

Hey ! Just to give a few feedbacks:
- I tried to use the [hourglass](https://github.com/spinalcordtoolbox/disc-labeling-hourglass) network with your data but unfortunately, the results are not really good.
- Then I tested a different approach called [SPINEPS](https://github.com/Hendrik-code/spineps) from a recent [paper](https://arxiv.org/abs/2402.16368) which is open source and I got really good results for T2w images only, here are few examples:

| sub-BB277_T2w.nii.gz | sub-DC293 | sub-DEV148Sujet01 | sub-MC224 |
|:---:|:---:|:---:|:---:|
|![Kapture 2024-03-01 at 14 28 14](https://github.com/sct-pipeline/spine-park/assets/68945192/b69fe77c-00a5-4bd2-a849-4bb6f9292101)|![Kapture 2024-03-01 at 14 31 31](https://github.com/sct-pipeline/spine-park/assets/68945192/d46d8561-dc1c-4664-9a5e-aa59994362e5)|![Kapture 2024-03-01 at 14 34 29](https://github.com/sct-pipeline/spine-park/assets/68945192/961e0d11-83c5-40ec-8190-d96f08352b1c)|![Kapture 2024-03-01 at 14 40 28](https://github.com/sct-pipeline/spine-park/assets/68945192/28fa5b7a-778a-4c23-97f2-0e64768c7ee9)|

I also wanted to test with other contrasts, but they managed to catch the contrast in the filename ahah.

> They are also using the [BIDS](https://bids-specification.readthedocs.io/en/stable/) standard

<img width="574" alt="Screenshot 2024-03-01 at 14 57 53" src="https://github.com/sct-pipeline/spine-park/assets/68945192/040fe356-2532-43f2-99f4-a8870579f535">

I could still technically rename the file to bypass this check but I don't really expect much since their models where only trained with T2w contrasts.

## Conclusion

It looks like we found a interesting model for vertebral labeling on T2w images ! Therefore, I will add this new method to the benchmark to evaluate its performances with different FOVs ! Also, for this project I could add an option to only extract the discs labels like we are doing with `sct_label_vertebrae`.

**Comment by jcohenadad** [comment]
> It looks like we found a interesting model for vertebral labeling on T2w images ! Therefore, I will add this new method to the benchmark to evaluate its performances with different FOVs ! Also, for this project I could add an option to only extract the discs labels like we are doing with sct_label_vertebrae

Amazing! yes, the next step is indeed to find a way to extract the disc labels. Maybe you can open an issue on SCT website so we can brainstorm on how to do this best? Eg: what if we use the current 'project label on centerline' feature from `sct_label_utils`?

**Comment by Kaonashi22** [comment]
Good news, thanks!
________________________________

**Comment by lydiachougar** [comment]
Hi! Any updates regarding the vertebral labeling?

**Comment by NathanMolinier** [comment]
Hi ! I am still experimenting on this but I will provide you some updates and inference code next week ! 
|Labeling based on discs segmentations|Output|
|:---:|:---:|
|![test1](https://github.com/sct-pipeline/spine-park/assets/68945192/f745d65d-9c12-4766-b05a-2e647aa2f92b)|![test2](https://github.com/sct-pipeline/spine-park/assets/68945192/64c80746-5257-4739-9f19-30eccc95fb7b)|

**Comment by Kaonashi22** [comment]
Sounds good, thank you!
________________________________

**Comment by NathanMolinier** [comment]
Sorry for the slight delay, but I'm actively working on a solution to make this vertebral labeling work on every contrast. For now, I can only provide you the [script](https://github.com/NathanMolinier/spineps/blob/main/simple_run.py) that I wrote, based on SPINEPS, to extract the discs of T2w images. (The output file with discs labels has the suffix `_label-discs_dlabel` in the output folder)

Regarding the [environment](https://github.com/NathanMolinier/spineps?tab=readme-ov-file#setup-venv) I just followed the instructions from SPINEPS. Also, the inference only works using the GPU.

If you encounter any issues with my script please let me know, I will try to fix it as soon as possible.

> Note: If the top of the spine is not visible in the image, the predicted labels won't be correct unfortunately

**Comment by Kaonashi22** [comment]
@NathanMolinier, thanks a lot!
@jcohenadad, should I run Nathan's script separately or add it to the main preprocessing script?

**Comment by NathanMolinier** [comment]
I personally think that you should run my script separately to avoid having SPINEPS as a dependency ! A more stable version will be implemented into the spinalcord toolbox.

**Comment by jcohenadad** [comment]
OK, to makes things easier and reproducible, I think that we should update the processing script to call SPINEPS instead of `sct_label_vertebrae`. 

To do this smoothly, the first step is for you to install SPINEPS and make sure it is callable from the Terminal. Once this is done, I will update the script to call SPINEPS.

**Comment by Kaonashi22** [comment]
Sounds good, I'll let you know how it works
________________________________

**Comment by Kaonashi22** [comment]
I finally succeeded to install SPINEPS. Hopefully it will be working well!

**Comment by jcohenadad** [comment]
Vertebral labeling will be done manually. See #26 #24 #21
